### ISSUE TITLE
Merge "Request to Mine" and "Resync" functions to one button

### ISSUE THREAD

**Issue by bellesitongliu** [philip-zhan/decentralized-social-network#33]
From user perspective, "request to mine" and "resync" should be one function called "refresh"

TODO: use one button called "refresh" to replace these two

**Comment by bellesitongliu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adding refresh button](https://trello.com/c/Puw7raVW/4-adding-refresh-button)

**Comment by zhoucong96** [comment]
commit f8cd06ec9fe7c26b75d448c9e45246c4f0938102
